### PR TITLE
expose MaybeTlsStream in async_tls

### PR DESCRIPTION
**Pull request by brandonros**

### CODE REVIEW

**Comment by brandonros** [comment]
this didn't work as expected/it isn't a dropin replacement

**Comment by sdroege** [comment]
What was the goal here, what are you trying to achieve?

**Comment by brandonros** [comment]
@sdroege  https://github.com/szarykott/signalrs/pull/13/files#diff-5cbc40981fc014f73fd685645609d74fb9b66af30b04026fced63702a08b34e0R13-R15

basically be able to swap out tokio for async-std / have them be easily interchangeable / drop in replacement

**Comment by sdroege** [comment]
Ah I see. Note that you can also use `async-tungstenite` with tokio

**Comment by brandonros** [comment]
is there any easy work we could do to expose MaybeTlsStream for async-std like you do tokio/the various TLS features? I guess exposing it is half the battle… there’s really no guarantee that it will be interchangeable.

**Comment by sdroege** [comment]
I'm not entirely sure what you need. Exposing this type seems fine to me, if that helps you anything.

**Pull request closed without merging**
