### PR TITLE
Update tokio to 0.3

### PR DESCRIPTION
**Pull request by nickelc**
I started on adding support for tokio 0.3 with a set of` tokio03-*` features.

Do you want to maintain tokio 0.2 support for future versions or just update to tokio 0.3?

### CODE REVIEW

**Comment by sdroege** [comment]
> Do you want to maintain tokio 0.2 support for future versions or just update to tokio 0.3?

I would just update to tokio 0.3, can you update the version to 0.10 in `Cargo.toml` for that? :) Thanks a lot!

**Comment by nickelc** [comment]
fine. basic update to 0.3 :+1: 

Can you release `0.9.2` for the current master? This should unblock some of my PRs.

**Comment by sdroege** [comment]
> Can you release `0.9.2` for the current master?

Yeah, on it. Don't let that block you though :)

**Comment by sdroege** [comment]
> Yeah, on it. Don't let that block you though :)

Done

Please let me know when this PR is ready for a review :)

**Comment by nickelc** [comment]
It's blocked by tokio-openssl. it's updated to tokio 0.3 but not released yet.

**Comment by sdroege** [comment]
Ok, just let me know when it's ready then :)

**Comment by nickelc** [comment]
PR is ready

**Pull request merged**
