### PR TITLE
bump tungstenite to 0.11

### PR DESCRIPTION
**Pull request by Licenser**

### CODE REVIEW

**Comment by sdroege** [comment]
Thanks!

**Comment by Licenser** [comment]
❤️thanks for the quick reply :D!

One last question. Is there a chance to get a 0.6 or 0.5.1 crate? :)

**Comment by sdroege** [comment]
Would have to be 0.6 (also because of the switch to tokio-native-tls), but sure. Just waiting for some feedback in https://github.com/sdroege/async-tungstenite/pull/21, or if I don't get any I'll update that one myself in the next days :)

**Comment by Licenser** [comment]
Great :D thanks!

**Pull request merged**
