### PR TITLE
Format code using 'cargo fmt'

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by sdroege** [comment]
Thanks! I didn't run `cargo fmt` because I wanted to be able to sync with `tokio-tungstenite` still in the future without having to worry about merge conflicts caused by formatting changes.

Once they enforce proper, automated formatting I'd merge this here too. Or once the two crates diverged enough, which hopefully will never happen :)

**Comment by Atul9** [comment]
ok, I have opened up a PR to format the new release at https://github.com/dbcfd/tokio-tungstenite/pull/4

**Comment by Atul9** [comment]
ok, I have opened up a PR to format the new release at https://github.com/dbcfd/tokio-tungstenite/pull/4 and mentioned it on https://github.com/snapview/tokio-tungstenite/pull/68#issuecomment-555108442

**Comment by sdroege** [comment]
Thanks! I've merged the formatting commit from the other repo now

**Pull request closed without merging**
